spring:
  application:
    name: knowledge-base
  profiles:
    active: dev,private
  data:
    redis:
      host: 192.168.13.128
      port: 6379
      database: 0
      timeout: 10s
      password: 123456
      repositories:
        enabled: false
      client-type: jedis
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_base
    username: root
    password: 851933hwk1523
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    authentication:
      username: neo4j
      password: 12345678
#    uri: bolt://localhost:7687
    uri: bolt://192.168.13.128:7687
  ai:
    # 阿里灵积
    dash-scope:
      api-key: sk-a0b02b385ae54b5d83c1f27ac55f6f89
      chat:
        options:
          incremental-output: false
          model: qwen-max
          # 多模态图片理解需要开启
#        api-key: sk-a0b02b385ae54b5d83c1f27ac55f6f89
      #          multi-model: true
      embedding:
        options:
          model: text-embedding-v2
      image:
        options:
          model: wanx-v1
    # 百度千帆 需要在pom.xml中放开qianfan starter的注释
    qian-fan:
      api-key: kcYDOH5hAVFfFaEs1tW4q17j
      secret-key: trrdPo6BaeoMAAvusifGbxYwcSMloMgm

    # openai 需要在pom.xml中放开openai starter的注释
    openai:
      api-key: xxx
    # 智谱清言 同样
    zhipuai:
      api-key: 2591ea9869b041cb97c4ce8177fca184.yHTD1ggWQ41dSyXE
    # kimi 同样
    moonshot:
      api-key: sk-flqhoYnskSVIuEcLqxa36xgH1M6jUqMeq0uqZIXgjYpF7eKW
    ollama:
      # 填写模型所在的地址
      base-url: http://localhost:11438
      chat:
        model: deepseek-r1:32b
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
code-assistant:
  project:
    project-path:
  arthas:
    url: http://localhost:8563/api
    password: arthas
    username: arthas
server:
  port: 9902
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 自动续签
  auto-renew: true
oss:
  provider: ali_yun
  # 阿里云oss配置
  ali-yun:
    access-key-id: LTAI5tB9iBafKCm7oN6t4aRA
    access-key-secret: y2mYRPgfYd2wtMLhyCDAu31ttQhXGR
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    bucket-name: panda-ergo
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi
      ui-path: /openapi-ui
  # 腾讯云oss配置
#  tencent:
#    bucket: xx
#    region: xx
#    secret-id: xx
#    secret-key: xx
